l_russian:
 at_artifact_price_qwa_desc: "Качество и цена"
 at_artifact_price_durability_desc: "Прочность"
 at_artifact_price_destroy_desc: "Обычные или шедевральные"
 at_artifact_price_unique_desc: "Уникальные"
 at_artifact_ask_price_player_desc: "Прибыль"
 at_artifact_ask_price_ai_greed_desc: "Жадность продавца"
 at_artifact_bid_price_ai_greed_desc: "Жадность покупателя"